### ISSUE TITLE
Membuat Adapter untuk list resep [ 8 point ]

### ISSUE THREAD

**Issue by iqbalprabu** [iqbalprabu/FoodRecipes-Eudeka#11]
buat adapter di package adapter ya, folder folder udh saya buat jadi tolong dicreate berdasarkan folder nya

oh ya untuk adapter ini tolong buat interface listener untuk on item click juga ya, buat nanti di implementasi ke activity

**Comment by alikhsan778** [comment]
Saya meninggalkan TODO untuk penggunaan function saya buat, untuk mempermudah cara baca, mungkin hehehehe :)
