### ISSUE TITLE
Membuat Pattern MVVM [ 8 Point ]

### ISSUE THREAD

**Issue by iqbalprabu** [iqbalprabu/FoodRecipes-Eudeka#2]
Membuat Pattern MVVM sesuai dengan contoh yang diberikan Euduka

[https://github.com/eudeka/osg3-android-1-mvvm](url)

**Comment by iqbalprabu** [comment]
mas @iboen mohon review nya apa aja yang kurang atau perlu di tambahkan dalam base MVVM ini

**Comment by iboen** [comment]
Udah ok untuk basenya
