### ISSUE TITLE
Membuat XML layout, untuk user menginput keyword pencarian resep makanan [ 5 Point ]

### ISSUE THREAD

**Issue by iqbalprabu** [iqbalprabu/FoodRecipes-Eudeka#3]
Membuat XML layout, untuk user menginput keyword pencarian resep makanan

1. Edit Text untuk input keyword
2. Button untuk action search ke Activity list resep makanan

<img width="246" alt="Screenshot 2019-03-13 at 9 57 55 PM" src="https://user-images.githubusercontent.com/16696807/54289351-93b86380-45db-11e9-97ee-bbf977aa41c3.png">

**Comment by alikhsan778** [comment]
im pickup

**Comment by alikhsan778** [comment]
Maaf Author commit masih mas iqbal, soalnya gk bisa diganti pakai punya saya
