### ISSUE TITLE
Membuat Repository untuk mengambil data dari API themealdb [ 8 Point ]

### ISSUE THREAD

**Issue by iqbalprabu** [iqbalprabu/FoodRecipes-Eudeka#9]
ini file nya udh saya buat, ada di file MealRepository.
kita ambil data nya dari sini ya

https://www.themealdb.com/

**Comment by iqbalprabu** [comment]
hai mas @Muhamadfikri20 saya sudah liat commit nya untuk repository ini

ada beberapa catatan sih menurut saya
1. Didalam repository sebisa mungkin hindari penggunaan Context, karna ini menurut yang pernah saya baca kodingan kita ga testable (agak sulit untuk diimpelementasikan unit testing)
2. Repository ini hanya mengolah data, jadi segala yang berhubungan dengan ui nanti aksi nya harus di activity mas.
3. Parameter search dalam fungsi getAllMeals ini bukan tipe nya Context tetapi String, karna ini digunakan untuk mengirim parameter yang user input

tolong di perbaharui ya mas

**Comment by iqbalprabu** [comment]
sebagai contoh mas fikri bisa llihat disini

https://github.com/eudeka/osg3-android-1-mvvm/blob/master/app/src/main/java/id/eudeka/osg3_klub_bola/data/TeamRepository.java

**Comment by Muhamadfikri20** [comment]
Thanks mas atas sarannya, nanti insya allah saya coba perbaiki
